### ISSUE TITLE
Installation aborted due to validation failure

### ISSUE THREAD

**Issue by kabads** [michael-milette/moodle-local_mailtest#15]
Is this now failing due to the GDPR privacy plugin?

```Install plugin from ZIP file

Validating local_mailtest ... Error
  [Error] Write access check [/var/www/html/local] 
Installation aborted due to validation failure
```

**Comment by michael-milette** [comment]
Hi Kabads,

Thanks for the great question. The installation is not failing due to GDPR privacy. It is failing because your web server does not have the Write permission required to create files and folders in the /var/www/html/local folder.

To resolve the problem, you can do one of the following:

- Grant the user under which the web server (e.g. Apache) runs sufficient permissions to be able to create and write the files and folders in the local folder. This will usually also include the ability for your web server to be able to Read the files.
- Transfer the plugin's files and folders using an SCP or FTP file transfer tool like WinSCP or Filezilla. Then adjust the permissions so that your web server can Read the files.
- Using a shell account, use GIT to download the files into place. Then adjust the permissions so that your web server can Read the files.

IMPORTANT: PHP files don't usually not need to be flagged as executable. Keep in mind that only fixing the permissions will provide Moodle with the ability to upgrade the plugins from within itself - if that is important to you.

Hope this helps. If you need any more help, feel free to re-open this issue on GitHub.

Best regards,

Michael

**Comment by MekaAtt** [comment]
[Error] Write access check [/var/www/html/local] 
Installation aborted due to validation failure

i need help

**Comment by michael-milette** [comment]
Hi @MekaAtt 

Did you read my previous reply? If you still need help with this Moodle installation issue, please contact me through my website at https://www.tngconsulting.ca/contact for premium support.

Best regards,

Michael

**Comment by Melsefy** [comment]
Hello,
I'm facing the same issue after updating to Moodle 4.4+. any solutions
"Validating local_o365 ... Error [Error] Write access check [/var/www/html/local] Installation aborted due to validation failure"
