### ISSUE TITLE
error 404

### ISSUE THREAD

**Issue by jmd87fr** [michael-milette/moodle-local_mailtest#26]
Hi,
I installed the plugin  on a Moodle Moodle 3.11.5 (Build: 20220117)
When I run admin/sever/email/ eMail Test
I have this page :-(

Not Found

The requested URL was not found on this server.

same result with 

- from moodle plugin database
- from this git repo

Could you help me ?

**Comment by michael-milette** [comment]
Hi @jmd87fr 

I will take a look. Did you install it from within Moodle or from a comma d prompt?

Michael

**Comment by jmd87fr** [comment]
I nstall from zip file from moodle

**Comment by michael-milette** [comment]
What is the name of the directory in which you put the files?

**Comment by jmd87fr** [comment]
I have not acces to the server 
admin > pulgin > install plugin > zip package

**Comment by michael-milette** [comment]
Hi @jmd87fr 

I just:

1. Downloaded local_mailtest_moodle.zip from https://moodle.org/plugins/local_mailtest/versions
2. Logged into my Moodle 3.11.5 site as an administrator.
3. Navigated to Site Administration > Plugins > Install plugins.
4. Installed the plugin.

It worked perfectly.

Based on what you have told me so far, I suspect that you may have an issue with the configuration of your webserver. It sounds like it is not recognizing index.php by default when no filename is specified. 

You can test this by going to the same URL that is giving you the 404 error and adding **index.php** at the end. For example, if the URL of the 404 error is:

https://example.com/local/mailtest/

...you would change it to:

https://example.com/local/mailtest/index.php

If this works, you will need to contact your webserver administrator and ask them to fix the problem. I strongly recommend that you do this as it will not only fix the problem here but in many other places in your Moodle site.

Best regards,

Michael

**Comment by jmd87fr** [comment]
I'll check that with the webmaster as soon as possible.
Thank you a lot

**Comment by michael-milette** [comment]
I have not heard back from you in over a month. I will therefore assume that the issue is resolved and close this issue.

Best regards,

Michael

**Comment by jmd87fr** [comment]
Hello Mickael, 
My apologies, I completely forgot to answer you. 
The problem is solved. 
Thanks for your help.
